name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  test-code:
    runs-on: ubuntu-latest
    container: akshaybabloo/mongodb

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Build the Docker image
        run: ./entrypoint.sh
        shell: bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        
