name: Mongo Test

on: [push]

jobs:
  mongo_tester_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mongo tester action
        uses: ./
        id: hello
