name: Mongo Test

on: [push]

jobs:

  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Pull and run MongoDB
      run: |
        docker pull mongo
        docker run mongo
